baseURL               = "https://nav.bioitee.com"
languageCode          = "zh-CN"
title                 = "yatengLG"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "docs"


[params]
    author        = "yatengLG"
    description   = "个人导航"
    siteurl       = "."
    upload        = "https://www.yuque.com/forms/share/1a1fee15-f7a9-4ee6-9dd4-b0ba9fef1871"  # 左侧导航栏的"网站提交"
    about         = "https://github.com/yatengLG/navigate"   # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/yatengLG/navigate"
    enablePreLoad = true		    		           # 网站完全打开前预加载动画
    textPreLoad   = "yatengLG 个人导航 WebStack-Hugo" 		# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = true                                          # 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			   # 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"             # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    baiduhmid     = ''             # 百度统计 hm.src 的 ID

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/LG.png"
    searchImageL      = "assets/images/bg-cartoon.jpg"		#搜索部分浅色背景图
    searchImageD      = "assets/images/bg-cartoon.jpg"		#搜索部分深色背景图
    logoExpandLight   = "assets/images/LG80x80-light.png"
    logoExpandDark    = "assets/images/LG80x80-dark.png"
    logoCollapseLight = "assets/images/LG80x80-light.png"
    logoCollapseDark  = "assets/images/LG80x80-dark.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = 'Power by [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | &copy; 2021 - {year} By yatengLG | [ 京ICP备2020046680号](http://beian.miit.gov.cn/)'
